// Generated by scripts/build.mjs. Do not edit by hand; edit data/*.json instead.
window.HOUSE_DATA = {
  "event": {
    "name": "SagaDAO House London",
    "edition": "Solana Breakpoint 2026",
    "city": "London",
    "area": "Kensington, near Olympia (W8 / W14)",
    "xHandle": "@SagaMobileDAO",
    "conference": {
      "name": "Solana Breakpoint 2026",
      "venue": "Olympia London, Hammersmith Road, W14 8UX",
      "start": "2026-11-15",
      "end": "2026-11-17"
    },
    "house": {
      "checkIn": "2026-11-14",
      "checkOut": "2026-11-20",
      "checkOutConfirmed": true,
      "address": null
    },
    "capacity": {
      "residents": 8,
      "attendees": 300,
      "sponsors": 12
    },
    "fxUsdPerGbp": 1.34,
    "keyDates": [
      {
        "date": "2026-10-02",
        "label": "House contract signed",
        "kind": "deadline"
      },
      {
        "date": "2026-10-02",
        "label": "Flagship venue decided (buyout or partner-hosted)",
        "kind": "deadline"
      },
      {
        "date": "2026-10-09",
        "label": "All residents invited, charter sent",
        "kind": "deadline"
      },
      {
        "date": "2026-10-16",
        "label": "Welcome kits and attendee gifts ordered",
        "kind": "deadline"
      },
      {
        "date": "2026-10-23",
        "label": "Sponsor sign-off for kit, print and branding",
        "kind": "deadline"
      },
      {
        "date": "2026-10-23",
        "label": "Temporary Event Notice(s) submitted",
        "kind": "deadline"
      },
      {
        "date": "2026-11-02",
        "label": "Guest dossiers sent",
        "kind": "deadline"
      },
      {
        "date": "2026-11-06",
        "label": "Run-of-show locked",
        "kind": "deadline"
      },
      {
        "date": "2026-11-14",
        "label": "Doors open: residents arrive",
        "kind": "milestone"
      },
      {
        "date": "2026-11-15",
        "label": "Breakpoint Day 1",
        "kind": "milestone"
      },
      {
        "date": "2026-11-18",
        "label": "SagaDAO Day (post-conference)",
        "kind": "milestone"
      },
      {
        "date": "2026-11-27",
        "label": "Hero film and sponsor reports out",
        "kind": "deadline"
      }
    ],
    "goals": [
      {
        "label": "Total spend within envelope",
        "target": 65000,
        "actual": null,
        "unit": "USD max"
      },
      {
        "label": "Sponsor revenue vs total cost",
        "target": 100,
        "actual": null,
        "unit": "%"
      },
      {
        "label": "Sponsors signed",
        "target": 12,
        "actual": 0,
        "unit": ""
      },
      {
        "label": "Sponsors who'd return",
        "target": 9,
        "actual": null,
        "unit": "of 12"
      },
      {
        "label": "Inbound sponsor enquiries within 30 days",
        "target": 10,
        "actual": 0,
        "unit": ""
      },
      {
        "label": "Programme attendance (unique)",
        "target": 300,
        "actual": null,
        "unit": ""
      },
      {
        "label": "Posts published during the week",
        "target": 150,
        "actual": 0,
        "unit": ""
      },
      {
        "label": "Median moment-to-post",
        "target": 120,
        "actual": null,
        "unit": "min"
      },
      {
        "label": "Resident charter compliance",
        "target": 8,
        "actual": null,
        "unit": "of 8"
      },
      {
        "label": "Guest NPS",
        "target": 70,
        "actual": null,
        "unit": ""
      }
    ],
    "fixes": [
      {
        "lesson": "Guests didn't know what was going on",
        "fix": "Charter, dossier, nightly briefing, 09:15 stand-up",
        "status": "planned"
      },
      {
        "lesson": "Free rooms, no expectations",
        "fix": "Room is complimentary in exchange for signed content commitments",
        "status": "planned"
      },
      {
        "lesson": "All party, nothing to sponsor",
        "fix": "Programme of sponsorable formats; party is the flagship night",
        "status": "planned"
      },
      {
        "lesson": "Slow, polished content that didn't convert",
        "fix": "Same-day engine, 2 h clips, 23:00 recap, CTAs and enquiry tracking",
        "status": "planned"
      },
      {
        "lesson": "Getting in didn't feel special",
        "fix": "Welcome kit, speech, named door welcome, gift, next-morning photos",
        "status": "planned"
      },
      {
        "lesson": "Overspent: props, a vehicle, a sponsor's karaoke machine, a refund request",
        "fix": "Locked props list, no special vehicle, sponsor extras billed to the sponsor, make-good-not-refund terms, 15% contingency",
        "status": "planned"
      }
    ],
    "openDecisions": [
      "Airbnb host: written OK (in Airbnb messages) for content filming and pre-approved gatherings of up to ~16?",
      "How many residents: 5 (a room each) or up to 8 (some sharing)? Depends on the listing's beds.",
      "Flagship venue: a minimum-spend bar or restaurant buyout near Olympia, or partner-hosted",
      "Flagship night: Mon 16 or Tue 17?",
      "Nightly rate stated in the charter",
      "Sponsor terms: payment schedule and no-cash-refund policy"
    ]
  },
  "tasks": {
    "areas": [
      "house",
      "sponsors",
      "guests",
      "programme",
      "content",
      "experiences",
      "arrival",
      "ops",
      "budget"
    ],
    "tasks": [
      {
        "id": "t000",
        "title": "Set up the planning hub (this repo)",
        "area": "ops",
        "due": "2026-09-23",
        "status": "done",
        "doc": "README.md"
      },
      {
        "id": "t001",
        "title": "Lock goals and targets",
        "area": "ops",
        "due": "2026-09-25",
        "status": "todo",
        "doc": "docs/vision.md"
      },
      {
        "id": "t002",
        "title": "Agree budget envelope: $50–65k",
        "area": "budget",
        "due": "2026-09-25",
        "status": "done",
        "doc": "docs/planning/budget.md"
      },
      {
        "id": "t003",
        "title": "Decide checkout: 20 Nov",
        "area": "house",
        "due": "2026-09-25",
        "status": "done",
        "doc": "docs/planning/decisions-log.md"
      },
      {
        "id": "t056",
        "title": "Vet the Airbnb: distance, “Where you'll sleep”, host's written OK for filming and gatherings",
        "area": "house",
        "due": "2026-09-28",
        "status": "todo",
        "doc": "docs/planning/house-and-venue.md"
      },
      {
        "id": "t057",
        "title": "Shortlist 3 min-spend buyout venues near Olympia for the flagship night",
        "area": "house",
        "due": "2026-09-30",
        "status": "todo",
        "doc": "docs/planning/house-and-venue.md"
      },
      {
        "id": "t004",
        "title": "Shortlist houses near Olympia (one candidate: $6k, 5 bed)",
        "area": "house",
        "due": "2026-09-25",
        "status": "doing",
        "doc": "docs/planning/house-and-venue.md"
      },
      {
        "id": "t005",
        "title": "Draft sponsorship packages: $15k / $10k / $5k",
        "area": "sponsors",
        "due": "2026-09-25",
        "status": "done",
        "doc": "docs/sponsors/packages.md"
      },
      {
        "id": "t006",
        "title": "Build prospect list: 30+ projects",
        "area": "sponsors",
        "due": "2026-09-26",
        "status": "todo",
        "doc": "docs/sponsors/playbook.md"
      },
      {
        "id": "t007",
        "title": "Shortlist 10–12 resident candidates for 8 places",
        "area": "guests",
        "due": "2026-09-26",
        "status": "todo",
        "doc": "docs/guests/guest-journey.md"
      },
      {
        "id": "t008",
        "title": "Reach out to production crew candidates",
        "area": "content",
        "due": "2026-09-26",
        "status": "todo",
        "doc": "docs/content/strategy.md"
      },
      {
        "id": "t009",
        "title": "Finish sponsor deck",
        "area": "sponsors",
        "due": "2026-09-30",
        "status": "todo",
        "doc": "docs/sponsors/packages.md"
      },
      {
        "id": "t058",
        "title": "Sponsor terms sheet: payment schedule, extras, make-good policy",
        "area": "sponsors",
        "due": "2026-09-30",
        "status": "todo",
        "doc": "docs/sponsors/terms.md"
      },
      {
        "id": "t010",
        "title": "Check Ceremony of the Keys availability",
        "area": "experiences",
        "due": "2026-09-30",
        "status": "todo",
        "doc": "docs/experiences/london-shortlist.md"
      },
      {
        "id": "t011",
        "title": "Sign the house, with written event and filming permission",
        "area": "house",
        "due": "2026-10-02",
        "status": "todo",
        "doc": "docs/planning/house-and-venue.md"
      },
      {
        "id": "t012",
        "title": "Decide flagship venue: min-spend buyout or partner-hosted",
        "area": "house",
        "due": "2026-10-02",
        "status": "todo",
        "doc": "docs/planning/house-and-venue.md"
      },
      {
        "id": "t013",
        "title": "Sponsor outreach wave 1 to all prospects",
        "area": "sponsors",
        "due": "2026-10-02",
        "status": "todo",
        "doc": "docs/sponsors/playbook.md"
      },
      {
        "id": "t014",
        "title": "House brand kit: wordmark, invitation design",
        "area": "content",
        "due": "2026-10-02",
        "status": "todo"
      },
      {
        "id": "t015",
        "title": "Book production crew",
        "area": "content",
        "due": "2026-10-02",
        "status": "todo",
        "doc": "docs/content/strategy.md"
      },
      {
        "id": "t016",
        "title": "Quotes: caterer, bar, SIA security, AV, cleaning, chauffeur",
        "area": "ops",
        "due": "2026-10-02",
        "status": "todo",
        "doc": "docs/planning/vendors.md"
      },
      {
        "id": "t017",
        "title": "Excursion enquiries, longest lead times first",
        "area": "experiences",
        "due": "2026-10-07",
        "status": "todo",
        "doc": "docs/experiences/london-shortlist.md"
      },
      {
        "id": "t018",
        "title": "Resident invitations and charter sent",
        "area": "guests",
        "due": "2026-10-09",
        "status": "todo",
        "doc": "docs/guests/house-charter.md"
      },
      {
        "id": "t019",
        "title": "Luma page live, applications open",
        "area": "arrival",
        "due": "2026-10-09",
        "status": "todo",
        "doc": "docs/attendees/arrival-experience.md"
      },
      {
        "id": "t020",
        "title": "Programme draft v1 and speaker wishlist",
        "area": "programme",
        "due": "2026-10-09",
        "status": "todo",
        "doc": "docs/programme/strategy.md"
      },
      {
        "id": "t021",
        "title": "Welcome kit design and sourcing; request sponsor inclusions",
        "area": "guests",
        "due": "2026-10-09",
        "status": "todo",
        "doc": "docs/guests/welcome-kit.md"
      },
      {
        "id": "t022",
        "title": "First sponsor signings and kickoff calls",
        "area": "sponsors",
        "due": "2026-10-09",
        "status": "todo",
        "doc": "docs/sponsors/playbook.md"
      },
      {
        "id": "t023",
        "title": "Order welcome kits and attendee gifts",
        "area": "guests",
        "due": "2026-10-16",
        "status": "todo",
        "doc": "docs/guests/welcome-kit.md"
      },
      {
        "id": "t024",
        "title": "Book caterer, bar, security and AV",
        "area": "ops",
        "due": "2026-10-16",
        "status": "todo",
        "doc": "docs/planning/vendors.md"
      },
      {
        "id": "t025",
        "title": "Invite speakers for every session",
        "area": "programme",
        "due": "2026-10-16",
        "status": "todo"
      },
      {
        "id": "t026",
        "title": "Book or hold excursions",
        "area": "experiences",
        "due": "2026-10-16",
        "status": "todo"
      },
      {
        "id": "t027",
        "title": "Send resident preference forms",
        "area": "guests",
        "due": "2026-10-16",
        "status": "todo",
        "doc": "docs/guests/preference-form.md"
      },
      {
        "id": "t028",
        "title": "Sponsor sign-off deadline",
        "area": "sponsors",
        "due": "2026-10-23",
        "status": "todo"
      },
      {
        "id": "t029",
        "title": "Submit Temporary Event Notice(s), if needed",
        "area": "ops",
        "due": "2026-10-23",
        "status": "todo",
        "doc": "docs/planning/risk-and-compliance.md"
      },
      {
        "id": "t030",
        "title": "Bind event insurance (public liability)",
        "area": "ops",
        "due": "2026-10-23",
        "status": "todo",
        "doc": "docs/planning/risk-and-compliance.md"
      },
      {
        "id": "t031",
        "title": "Speakers confirmed; programme v2",
        "area": "programme",
        "due": "2026-10-23",
        "status": "todo"
      },
      {
        "id": "t032",
        "title": "Draft chauffeur schedule from flights",
        "area": "ops",
        "due": "2026-10-23",
        "status": "todo"
      },
      {
        "id": "t033",
        "title": "Personalisation plan per resident",
        "area": "guests",
        "due": "2026-10-23",
        "status": "todo"
      },
      {
        "id": "t034",
        "title": "Publish programme; open session RSVPs",
        "area": "programme",
        "due": "2026-10-28",
        "status": "todo"
      },
      {
        "id": "t035",
        "title": "Content templates and shared drive ready",
        "area": "content",
        "due": "2026-10-30",
        "status": "todo",
        "doc": "docs/content/strategy.md"
      },
      {
        "id": "t036",
        "title": "Lock content calendar; map sponsor deliverables",
        "area": "content",
        "due": "2026-10-30",
        "status": "todo"
      },
      {
        "id": "t059",
        "title": "Lock the props and styling list; nothing bought off-list",
        "area": "budget",
        "due": "2026-10-30",
        "status": "todo",
        "doc": "docs/planning/budget.md"
      },
      {
        "id": "t037",
        "title": "Draft welcome speech",
        "area": "guests",
        "due": "2026-10-30",
        "status": "todo",
        "doc": "docs/concierge/welcome-speech.md"
      },
      {
        "id": "t038",
        "title": "Print order: cards, signage, menus",
        "area": "arrival",
        "due": "2026-10-30",
        "status": "todo"
      },
      {
        "id": "t039",
        "title": "\"Partner with us\" page live",
        "area": "sponsors",
        "due": "2026-10-30",
        "status": "todo",
        "doc": "docs/content/strategy.md"
      },
      {
        "id": "t040",
        "title": "Send guest dossiers",
        "area": "guests",
        "due": "2026-11-02",
        "status": "todo",
        "doc": "docs/guests/guest-journey.md"
      },
      {
        "id": "t041",
        "title": "Open resident WhatsApp group",
        "area": "guests",
        "due": "2026-11-02",
        "status": "todo"
      },
      {
        "id": "t042",
        "title": "Staff and crew briefing pack",
        "area": "ops",
        "due": "2026-11-04",
        "status": "todo",
        "doc": "docs/concierge/service-standards.md"
      },
      {
        "id": "t043",
        "title": "Lock run-of-show",
        "area": "programme",
        "due": "2026-11-06",
        "status": "todo"
      },
      {
        "id": "t044",
        "title": "Neighbour letters delivered",
        "area": "house",
        "due": "2026-11-06",
        "status": "todo",
        "doc": "docs/planning/risk-and-compliance.md"
      },
      {
        "id": "t045",
        "title": "Assemble and personalise welcome kits",
        "area": "guests",
        "due": "2026-11-12",
        "status": "todo"
      },
      {
        "id": "t046",
        "title": "Final attendee confirmations; export door lists",
        "area": "arrival",
        "due": "2026-11-12",
        "status": "todo"
      },
      {
        "id": "t047",
        "title": "Tech rehearsal plan: studio, stream, Wi-Fi",
        "area": "content",
        "due": "2026-11-12",
        "status": "todo"
      },
      {
        "id": "t048",
        "title": "Print emergency sheet",
        "area": "ops",
        "due": "2026-11-12",
        "status": "todo",
        "doc": "docs/concierge/emergency.md"
      },
      {
        "id": "t049",
        "title": "Confirm every car; send pickup messages",
        "area": "ops",
        "due": "2026-11-13",
        "status": "todo"
      },
      {
        "id": "t050",
        "title": "Thank-yous and photo galleries sent",
        "area": "arrival",
        "due": "2026-11-21",
        "status": "todo"
      },
      {
        "id": "t051",
        "title": "Personal content packs to residents",
        "area": "content",
        "due": "2026-11-21",
        "status": "todo"
      },
      {
        "id": "t052",
        "title": "Publish hero film",
        "area": "content",
        "due": "2026-11-27",
        "status": "todo"
      },
      {
        "id": "t053",
        "title": "Deliver sponsor reports",
        "area": "sponsors",
        "due": "2026-11-27",
        "status": "todo",
        "doc": "docs/post-event/sponsor-report-template.md"
      },
      {
        "id": "t054",
        "title": "Charter reconciliation",
        "area": "guests",
        "due": "2026-11-30",
        "status": "todo",
        "doc": "docs/guests/house-charter.md"
      },
      {
        "id": "t055",
        "title": "Retro and next-house outreach",
        "area": "ops",
        "due": "2026-12-04",
        "status": "todo",
        "doc": "docs/post-event/retro-template.md"
      }
    ]
  },
  "sponsors": {
    "stages": [
      "prospect",
      "contacted",
      "talks",
      "signed",
      "paid",
      "delivered",
      "lost"
    ],
    "tiers": [
      {
        "id": "founding",
        "name": "Founding Partner",
        "slots": 2,
        "priceUsd": 15000,
        "owns": [
          "Saga Sessions Night 1",
          "Saga Sessions Night 2",
          "Co-presents the flagship night"
        ]
      },
      {
        "id": "programme",
        "name": "Programme Partner",
        "slots": 4,
        "priceUsd": 10000,
        "owns": [
          "Demo Hour",
          "House Studio",
          "Builder Breakfast",
          "Closed Door roundtable",
          "Welcome Dinner"
        ]
      },
      {
        "id": "experience",
        "name": "Experience Partner",
        "slots": 6,
        "priceUsd": 5000,
        "owns": [
          "Resident Dinner",
          "Farewell Dinner",
          "Welcome Kit",
          "Arrival Moment",
          "London excursion",
          "Office Hours",
          "Attendee gift"
        ]
      }
    ],
    "sponsors": [],
    "dubaiTiersUsd": [
      10000,
      5000,
      2500
    ]
  },
  "guests": {
    "statuses": [
      "shortlist",
      "invited",
      "accepted",
      "declined"
    ],
    "rooms": [
      {
        "id": "01",
        "beds": 2
      },
      {
        "id": "02",
        "beds": 2
      },
      {
        "id": "03",
        "beds": 2
      },
      {
        "id": "04",
        "beds": 1
      },
      {
        "id": "05",
        "beds": 1
      }
    ],
    "roomsNote": "Assumed layout. Check the Airbnb listing's “Where you'll sleep” section and update the beds per room.",
    "commitmentTargets": {
      "posts": 6,
      "amplify": 6,
      "studio": 1,
      "role": 1,
      "flagship": 1,
      "dinners": 2
    },
    "guests": []
  },
  "programme": {
    "formats": [
      "arrival",
      "breakfast",
      "session",
      "studio",
      "demo",
      "closed-door",
      "office-hours",
      "flagship",
      "dinner",
      "experience",
      "ops"
    ],
    "days": [
      {
        "date": "2026-11-14",
        "label": "Arrival",
        "items": [
          {
            "time": "All day",
            "title": "Airport pickups: name boards, water, chargers",
            "format": "arrival",
            "audience": "Residents",
            "status": "draft"
          },
          {
            "time": "14:00",
            "title": "Arrival ritual: named greeting, drink, tour, note, welcome kit",
            "format": "arrival",
            "audience": "Residents",
            "status": "draft"
          },
          {
            "time": "17:30",
            "title": "Content onboarding: charter, week, drive, WhatsApp",
            "format": "ops",
            "audience": "Residents",
            "status": "draft"
          },
          {
            "time": "19:30",
            "title": "Welcome Dinner and welcome speech",
            "format": "dinner",
            "audience": "Residents + Founding Partners",
            "status": "draft"
          },
          {
            "time": "21:30",
            "title": "First nightly briefing",
            "format": "ops",
            "audience": "Residents",
            "status": "draft"
          }
        ]
      },
      {
        "date": "2026-11-15",
        "label": "Breakpoint Day 1",
        "items": [
          {
            "time": "07:45",
            "title": "Builder Breakfast #1",
            "format": "breakfast",
            "audience": "25 invited",
            "capacity": 25,
            "status": "draft"
          },
          {
            "time": "09:15",
            "title": "Stand-up",
            "format": "ops",
            "audience": "Residents",
            "status": "draft"
          },
          {
            "time": "10:00",
            "title": "House Studio recording",
            "format": "studio",
            "audience": "Speakers",
            "status": "draft"
          },
          {
            "time": "18:30",
            "title": "Saga Sessions: Night 1 (streamed)",
            "format": "session",
            "audience": "80–150",
            "capacity": 150,
            "status": "draft"
          },
          {
            "time": "20:30",
            "title": "Resident Dinner",
            "format": "dinner",
            "audience": "Residents + guests",
            "status": "draft"
          }
        ]
      },
      {
        "date": "2026-11-16",
        "label": "Breakpoint Day 2",
        "items": [
          {
            "time": "07:45",
            "title": "Builder Breakfast #2",
            "format": "breakfast",
            "audience": "25 invited",
            "capacity": 25,
            "status": "draft"
          },
          {
            "time": "09:15",
            "title": "Stand-up",
            "format": "ops",
            "audience": "Residents",
            "status": "draft"
          },
          {
            "time": "10:00",
            "title": "House Studio recording",
            "format": "studio",
            "audience": "Speakers",
            "status": "draft"
          },
          {
            "time": "14:00",
            "title": "Office Hours",
            "format": "office-hours",
            "audience": "1:1 bookings",
            "status": "draft"
          },
          {
            "time": "19:00",
            "title": "Flagship Night (or Tue 17, decision open)",
            "format": "flagship",
            "audience": "300+",
            "capacity": 300,
            "status": "draft"
          }
        ]
      },
      {
        "date": "2026-11-17",
        "label": "Breakpoint Day 3",
        "items": [
          {
            "time": "07:45",
            "title": "Closed Door roundtable",
            "format": "closed-door",
            "audience": "14 invited",
            "capacity": 14,
            "status": "draft"
          },
          {
            "time": "09:15",
            "title": "Stand-up",
            "format": "ops",
            "audience": "Residents",
            "status": "draft"
          },
          {
            "time": "10:00",
            "title": "House Studio recording",
            "format": "studio",
            "audience": "Speakers",
            "status": "draft"
          },
          {
            "time": "18:30",
            "title": "Saga Sessions: Night 2 (streamed)",
            "format": "session",
            "audience": "80–150",
            "capacity": 150,
            "status": "draft"
          }
        ]
      },
      {
        "date": "2026-11-18",
        "label": "SagaDAO Day",
        "items": [
          {
            "time": "10:00",
            "title": "Slow breakfast",
            "format": "ops",
            "audience": "Residents",
            "status": "draft"
          },
          {
            "time": "13:00",
            "title": "Demo Hour: 5 projects, 5 minutes, live judging",
            "format": "demo",
            "audience": "100+",
            "capacity": 120,
            "status": "draft"
          },
          {
            "time": "15:00",
            "title": "Closed Door #2 or workshop",
            "format": "closed-door",
            "audience": "14 invited",
            "capacity": 14,
            "status": "draft"
          },
          {
            "time": "Evening",
            "title": "London experience",
            "format": "experience",
            "audience": "Residents",
            "status": "draft"
          }
        ]
      },
      {
        "date": "2026-11-19",
        "label": "London day and farewell",
        "items": [
          {
            "time": "Daytime",
            "title": "Excursion (choice of two)",
            "format": "experience",
            "audience": "Residents",
            "status": "draft"
          },
          {
            "time": "19:30",
            "title": "Farewell Dinner",
            "format": "dinner",
            "audience": "Residents + partners",
            "status": "draft"
          }
        ]
      },
      {
        "date": "2026-11-20",
        "label": "Departures",
        "items": [
          {
            "time": "07:00",
            "title": "Farewell breakfast, departure gifts, cars",
            "format": "arrival",
            "audience": "Residents",
            "status": "draft"
          }
        ]
      }
    ]
  },
  "experiences": {
    "statuses": [
      "idea",
      "enquired",
      "held",
      "booked",
      "cancelled"
    ],
    "experiences": [
      {
        "id": "thames-boat",
        "title": "Private Thames boat at dusk",
        "kind": "signature",
        "status": "idea",
        "leadTime": "2–3 weeks",
        "estCostGbp": 3000,
        "sponsorable": true,
        "content": "excellent",
        "notes": "Board around 15:15 for sunset at about 16:10"
      },
      {
        "id": "savile-row",
        "title": "Savile Row bespoke visit and fitting",
        "kind": "signature",
        "status": "idea",
        "leadTime": "2–4 weeks",
        "estCostGbp": 2500,
        "sponsorable": true,
        "content": "strong"
      },
      {
        "id": "chefs-table",
        "title": "Private dining room for the Farewell Dinner",
        "kind": "signature",
        "status": "idea",
        "leadTime": "3–4 weeks",
        "estCostGbp": 4000,
        "sponsorable": true,
        "content": "strong"
      },
      {
        "id": "ceremony-keys",
        "title": "Ceremony of the Keys, Tower of London",
        "kind": "signature",
        "status": "idea",
        "leadTime": "Months (check now)",
        "estCostGbp": 0,
        "sponsorable": false,
        "content": "none",
        "notes": "No filming allowed"
      },
      {
        "id": "horizon-22",
        "title": "Horizon 22 or Sky Garden viewing",
        "kind": "signature",
        "status": "idea",
        "leadTime": "When slots release",
        "estCostGbp": 0,
        "sponsorable": false,
        "content": "strong"
      },
      {
        "id": "borough-roast",
        "title": "Borough Market walk plus a historic pub roast",
        "kind": "relaxed",
        "status": "idea",
        "leadTime": "1 week",
        "estCostGbp": 900,
        "sponsorable": false,
        "content": "good"
      },
      {
        "id": "sauna",
        "title": "Sauna and cold plunge reset",
        "kind": "relaxed",
        "status": "idea",
        "leadTime": "1–2 weeks",
        "estCostGbp": 600,
        "sponsorable": true,
        "content": "good"
      },
      {
        "id": "park-run",
        "title": "Morning run in Holland Park, then coffee",
        "kind": "relaxed",
        "status": "idea",
        "leadTime": "None",
        "estCostGbp": 100,
        "sponsorable": false,
        "content": "good"
      },
      {
        "id": "padel",
        "title": "Padel session",
        "kind": "relaxed",
        "status": "idea",
        "leadTime": "1 week",
        "estCostGbp": 400,
        "sponsorable": true,
        "content": "good"
      },
      {
        "id": "private-view",
        "title": "Private view: Leighton House or the Design Museum",
        "kind": "relaxed",
        "status": "idea",
        "leadTime": "2–3 weeks",
        "estCostGbp": 2000,
        "sponsorable": true,
        "content": "strong"
      },
      {
        "id": "tasting",
        "title": "Gin or whisky tasting",
        "kind": "relaxed",
        "status": "idea",
        "leadTime": "1–2 weeks",
        "estCostGbp": 800,
        "sponsorable": true,
        "content": "moderate"
      }
    ]
  },
  "content": {
    "slas": [
      {
        "layer": "Moment clip",
        "target": "Within 2 h"
      },
      {
        "layer": "Daily recap",
        "target": "By 23:00"
      },
      {
        "layer": "Studio clips",
        "target": "Same day"
      },
      {
        "layer": "Studio episode",
        "target": "Within 48 h"
      },
      {
        "layer": "Hero film",
        "target": "Within 7 days"
      }
    ],
    "baseline": {
      "followers": null,
      "note": "Record the @SagaMobileDAO follower count on 13 Nov"
    },
    "metrics": [
      {
        "key": "posts",
        "label": "Posts published",
        "target": 150,
        "actual": 0
      },
      {
        "key": "medianMinutes",
        "label": "Median minutes to post",
        "target": 120,
        "actual": null,
        "lowerIsBetter": true
      },
      {
        "key": "impressions",
        "label": "Impressions",
        "target": null,
        "actual": 0
      },
      {
        "key": "followers",
        "label": "Followers gained",
        "target": null,
        "actual": 0
      },
      {
        "key": "registrations",
        "label": "Luma registrations from content",
        "target": null,
        "actual": 0
      },
      {
        "key": "enquiries",
        "label": "Inbound sponsor enquiries",
        "target": 10,
        "actual": 0
      }
    ],
    "log": []
  },
  "budget": {
    "currency": "GBP",
    "note": "Planned inside the $50–65k envelope with a 15% contingency. House is a real quote; everything else is an estimate until quoted.",
    "lines": [
      {
        "id": "house",
        "category": "House",
        "item": "Airbnb house: 5 bedrooms, 14–20 Nov ($6,000 USD quote; confirm fees)",
        "plannedGbp": 4480,
        "committedGbp": 0,
        "paidGbp": 0,
        "estimate": false
      },
      {
        "id": "venue",
        "category": "Venue",
        "item": "Flagship venue: min-spend buyout or partner-hosted",
        "plannedGbp": 5000,
        "committedGbp": 0,
        "paidGbp": 0,
        "estimate": true
      },
      {
        "id": "catering",
        "category": "Food & drink",
        "item": "Resident breakfasts and 3 dinners",
        "plannedGbp": 3500,
        "committedGbp": 0,
        "paidGbp": 0,
        "estimate": true
      },
      {
        "id": "flagship-fb",
        "category": "Food & drink",
        "item": "Flagship night bar and food (counts toward min spend)",
        "plannedGbp": 6000,
        "committedGbp": 0,
        "paidGbp": 0,
        "estimate": true
      },
      {
        "id": "security",
        "category": "Operations",
        "item": "SIA door staff, flagship night",
        "plannedGbp": 2000,
        "committedGbp": 0,
        "paidGbp": 0,
        "estimate": true
      },
      {
        "id": "production",
        "category": "Content",
        "item": "Shooter-editor, photographer, edit",
        "plannedGbp": 5000,
        "committedGbp": 0,
        "paidGbp": 0,
        "estimate": true
      },
      {
        "id": "studio-av",
        "category": "Content",
        "item": "Studio kit hire, mics, stream",
        "plannedGbp": 1500,
        "committedGbp": 0,
        "paidGbp": 0,
        "estimate": true
      },
      {
        "id": "kits",
        "category": "Hospitality",
        "item": "Resident welcome kits (8 × £300)",
        "plannedGbp": 2400,
        "committedGbp": 0,
        "paidGbp": 0,
        "estimate": true
      },
      {
        "id": "gifts",
        "category": "Hospitality",
        "item": "Attendee gifts (300 × £8)",
        "plannedGbp": 2400,
        "committedGbp": 0,
        "paidGbp": 0,
        "estimate": true
      },
      {
        "id": "excursions",
        "category": "Hospitality",
        "item": "Excursions (aim for partner-funded)",
        "plannedGbp": 1500,
        "committedGbp": 0,
        "paidGbp": 0,
        "estimate": true
      },
      {
        "id": "transport",
        "category": "Operations",
        "item": "Cars: airport and excursions (no special vehicle)",
        "plannedGbp": 1500,
        "committedGbp": 0,
        "paidGbp": 0,
        "estimate": true
      },
      {
        "id": "staff",
        "category": "Operations",
        "item": "House manager and housekeeping",
        "plannedGbp": 2000,
        "committedGbp": 0,
        "paidGbp": 0,
        "estimate": true
      },
      {
        "id": "print",
        "category": "Hospitality",
        "item": "Print, signage, florals, props (locked list by 30 Oct)",
        "plannedGbp": 1500,
        "committedGbp": 0,
        "paidGbp": 0,
        "estimate": true
      },
      {
        "id": "insurance",
        "category": "Operations",
        "item": "Insurance and licensing",
        "plannedGbp": 800,
        "committedGbp": 0,
        "paidGbp": 0,
        "estimate": true
      },
      {
        "id": "contingency",
        "category": "Contingency",
        "item": "15% contingency (Dubai's surprises cost $5–10k)",
        "plannedGbp": 5937,
        "committedGbp": 0,
        "paidGbp": 0,
        "estimate": true
      }
    ],
    "envelopeUsd": {
      "low": 50000,
      "high": 65000
    },
    "dubaiUsd": {
      "actual": 55000,
      "shouldHaveBeen": 40000
    }
  }
};
window.HOUSE_BUILT_AT = "2026-09-23T16:51:22.316Z";
