#!/usr/bin/env node
// Validates data/*.json and regenerates dashboard/data.js.
//
//   node scripts/build.mjs                        validate + write dashboard/data.js
//   node scripts/build.mjs --check                validate only
//   node scripts/build.mjs --single <out.html>    also write a single-file dashboard
//                                                 (CSS, JS and data inlined, no <html>/<body> wrapper)

import { readFileSync, writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const root = join(dirname(fileURLToPath(import.meta.url)), '..');
const FILES = ['event', 'tasks', 'sponsors', 'guests', 'programme', 'experiences', 'content', 'budget'];
const DATE = /^\d{4}-\d{2}-\d{2}$/;

const errors = [];
const fail = (file, msg) => errors.push(`data/${file}.json: ${msg}`);

const data = {};
for (const name of FILES) {
  try {
    data[name] = JSON.parse(readFileSync(join(root, 'data', `${name}.json`), 'utf8'));
  } catch (e) {
    fail(name, `could not parse (${e.message})`);
  }
}
if (errors.length) report();

const isDate = (v) => typeof v === 'string' && DATE.test(v) && !Number.isNaN(Date.parse(v));
const checkDate = (file, where, v, optional = false) => {
  if (optional && (v === null || v === undefined || v === '')) return;
  if (!isDate(v)) fail(file, `${where}: "${v}" is not a YYYY-MM-DD date`);
};
const checkEnum = (file, where, v, allowed) => {
  if (!allowed.includes(v)) fail(file, `${where}: "${v}" must be one of ${allowed.join(', ')}`);
};
const checkUniqueIds = (file, list) => {
  const seen = new Set();
  for (const item of list) {
    if (!item.id) fail(file, `an entry is missing "id"`);
    else if (seen.has(item.id)) fail(file, `duplicate id "${item.id}"`);
    seen.add(item.id);
  }
};

// event
const { event, tasks, sponsors, guests, programme, experiences, budget } = data;
checkDate('event', 'conference.start', event.conference?.start);
checkDate('event', 'conference.end', event.conference?.end);
checkDate('event', 'house.checkIn', event.house?.checkIn);
checkDate('event', 'house.checkOut', event.house?.checkOut);
if (!(event.fxUsdPerGbp > 0)) fail('event', 'fxUsdPerGbp must be a positive number');
(event.keyDates || []).forEach((k, i) => checkDate('event', `keyDates[${i}]`, k.date));

// tasks
checkUniqueIds('tasks', tasks.tasks);
for (const t of tasks.tasks) {
  checkDate('tasks', `${t.id}.due`, t.due);
  checkEnum('tasks', `${t.id}.status`, t.status, ['todo', 'doing', 'blocked', 'done']);
  checkEnum('tasks', `${t.id}.area`, t.area, tasks.areas);
}

// sponsors
const tierIds = sponsors.tiers.map((t) => t.id);
checkUniqueIds('sponsors', sponsors.sponsors);
for (const s of sponsors.sponsors) {
  checkEnum('sponsors', `${s.id}.stage`, s.stage, sponsors.stages);
  if (s.tier) checkEnum('sponsors', `${s.id}.tier`, s.tier, tierIds);
  checkDate('sponsors', `${s.id}.nextStepDue`, s.nextStepDue, true);
  (s.deliverables || []).forEach((d, i) => checkDate('sponsors', `${s.id}.deliverables[${i}].due`, d.due, true));
}

// guests
checkUniqueIds('guests', guests.guests);
const rooms = new Map();
for (const g of guests.guests) {
  checkEnum('guests', `${g.id}.status`, g.status, guests.statuses);
  if (g.room !== null && g.room !== undefined) {
    if (!/^\d{2}$/.test(g.room) || +g.room < 1 || +g.room > event.capacity.residents) {
      fail('guests', `${g.id}.room "${g.room}" must be "01"–"${String(event.capacity.residents).padStart(2, '0')}" or null`);
    } else if (rooms.has(g.room)) {
      fail('guests', `room ${g.room} is assigned to both ${rooms.get(g.room)} and ${g.id}`);
    } else rooms.set(g.room, g.id);
  }
  checkDate('guests', `${g.id}.arrival.date`, g.arrival?.date, true);
  checkDate('guests', `${g.id}.departure.date`, g.departure?.date, true);
}

// programme
for (const d of programme.days) {
  checkDate('programme', `days[${d.date}]`, d.date);
  d.items.forEach((it, i) => {
    checkEnum('programme', `${d.date}.items[${i}].format`, it.format, programme.formats);
    checkEnum('programme', `${d.date}.items[${i}].status`, it.status, ['draft', 'confirmed', 'cancelled']);
  });
}

// experiences
checkUniqueIds('experiences', experiences.experiences);
for (const x of experiences.experiences) checkEnum('experiences', `${x.id}.status`, x.status, experiences.statuses);

// budget
checkUniqueIds('budget', budget.lines);
for (const l of budget.lines) {
  for (const k of ['plannedGbp', 'committedGbp', 'paidGbp']) {
    if (typeof l[k] !== 'number' || l[k] < 0) fail('budget', `${l.id}.${k} must be a number ≥ 0`);
  }
}

report();

const args = process.argv.slice(2);
if (args.includes('--check')) {
  console.log('✓ data/ is valid');
  process.exit(0);
}

const builtAt = new Date().toISOString();
const js = `// Generated by scripts/build.mjs. Do not edit by hand; edit data/*.json instead.\nwindow.HOUSE_DATA = ${JSON.stringify(data, null, 2)};\nwindow.HOUSE_BUILT_AT = ${JSON.stringify(builtAt)};\n`;
writeFileSync(join(root, 'dashboard', 'data.js'), js);
console.log('✓ data/ is valid → dashboard/data.js written');

const singleIdx = args.indexOf('--single');
if (singleIdx !== -1) {
  const out = args[singleIdx + 1];
  if (!out) {
    console.error('--single needs an output path');
    process.exit(1);
  }
  const html = readFileSync(join(root, 'dashboard', 'index.html'), 'utf8');
  const css = readFileSync(join(root, 'dashboard', 'styles.css'), 'utf8');
  const app = readFileSync(join(root, 'dashboard', 'app.js'), 'utf8');
  const head = html.match(/<head>([\s\S]*?)<\/head>/)[1]
    .replace(/<meta charset[^>]*>\s*/i, '')
    .replace(/<meta name="viewport"[^>]*>\s*/i, '')
    .replace(/<link rel="stylesheet" href="styles.css">/, () => `<style>\n${css}\n</style>`);
  const body = html.match(/<body[^>]*>([\s\S]*?)<\/body>/)[1]
    .replace(/<script src="data.js"><\/script>/, () => `<script>\n${js}\n</script>`)
    .replace(/<script src="app.js"><\/script>/, () => `<script>\n${app}\n</script>`);
  writeFileSync(out, `${head.trim()}\n${body.trim()}\n`);
  console.log(`✓ single-file dashboard → ${out}`);
}

function report() {
  if (!errors.length) return;
  console.error(`✗ ${errors.length} problem${errors.length > 1 ? 's' : ''} in data/:`);
  for (const e of errors) console.error(`  - ${e}`);
  process.exit(1);
}
